run:
  build-tags:
    - dbtest

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - gocritic
    - goimports
    - goprintffuncname
    - gosimple
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/baur/v3
