linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - exportloopref
    - goimports
    - golint
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/baur/v1
